### Imports needed

In [2]:
from sklearn import preprocessing

import numpy as np

In [3]:
x = np.array([[1., -1., 2.],[2., 0., 0.], [0., 1., -1.]])

In [6]:
x_scaled = preprocessing.scale(x)
print(x_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [8]:
print(x_scaled.mean(axis=0))
print(x_scaled.std(axis=0))

[0. 0. 0.]
[1. 1. 1.]


### We can't use extend scale on testing data. So we use StandardSacler

In [12]:
scaler = preprocessing.StandardScaler()

scaler.fit(x) #learns parameter

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [14]:
x_test = [[1, 1, 0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])