## Here we implement neural Network for XOR operation 
- XOR requires hidden layer as it is not linearly separable

### Imports 

In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,1,1,0]]).T

### Sigmoid function

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

### Derivative of sigmoid

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

### Initialize weights for NN having 1 hidden layer

In [16]:
wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2)) - 1
wo = 2*np.random.random((2,1)) - 1
bo = 2*np.random.random((1,1)) - 1
lr = 0.1 # learning Rate

In [17]:
for iter in range(10000):
    # Forward propagation to find output
    output0 = X
    inputHidden = np.dot(output0, wh)+bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden, wo)+bo
    output = sig(inputForOutputLayer)
        
    first_term_output_layer = output - Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer
    
    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis=0, keepdims=True)
    
    
    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer
    
    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis=0, keepdims=True)
    
    
    
    # Update weights and biases
    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias
    
    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias
    

### Now our Neural Network would have learn all weights which minimizes the error. So lets check output on this trained neural network

In [18]:
output0 = X
inputHidden = np.dot(output0, wh)+bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden, wo)+bo
output = sig(inputForOutputLayer)
output

array([[0.04585102],
       [0.94546535],
       [0.94550366],
       [0.05405999]])

In [19]:
print(wo,bo)

[[-7.84641681]
 [-7.74347483]] [[3.83887343]]


In [20]:
print(wh,bh)

[[ 3.98171868 -5.61679705]
 [ 3.97930634 -5.6051214 ]] [[-6.19539969  2.04746961]]
