### Imports 

In [1]:
import numpy as np

In [2]:
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0,0,0,1]]).T

In [3]:
print(x.shape, y.shape)

(4, 2) (4, 1)


### Sigmoid function

In [13]:
def sig(z):
    return 1/(1+np.exp(-z))

### Derivative of sigmoid

In [14]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

### Initialize weights without any hidden layer
- We want to initialize within range [-1, 1]

In [16]:
weights = 2* np.random.random((2,1)) - 1
bias = 2* np.random.random(1) - 1 # Only1 bias bcz this is the simplestneural network without any hidden layer
lr = 0.1 # learning rate

### Forward Propagation 
- output0 = x  # output of input layers can be thought of as input (feaures) given
- output = sig(np.dot( output0 ,weights) + bias)

### Implement neural network without hidden layer

In [18]:
for iter in range(10000):
    output0 = x
    output = sig(np.dot(output0, weights)+bias)
    
    first_term = output-y
    input_for_last_layer = np.dot(output0, weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term*second_term
    
    changes = np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]*output0[j][i]
            
    # Update weights
    weights = weights - lr*changes
    
    
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0]*1
            
    # Update Bias
    bias = bias - lr*bias_change

### Now our Neural Network would have learn all weights which minimizes the error. So lets check output on this trained neural network

In [19]:
output = sig(np.dot(x,weights)+bias)

In [21]:
output

array([[2.47897105e-04],
       [5.57649261e-02],
       [5.57649265e-02],
       [9.33627132e-01]])

In [22]:
print(weights, bias)

[[5.47301883]
 [5.47301882]] [-8.30224887]


### Optimize Code Using Vector Operations
- In above code we use for loops which are hard coded i.e j run 4 times. Now we modify our code sucht that it works for any number of data points

In [23]:
for iter in range(10000):
    output0 = x
    output = sig(np.dot(output0, weights)+bias)
    
    first_term = output-y
    input_for_last_layer = np.dot(output0, weights)+bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term*second_term
    
    changes = np.dot(output0.T, first_two)
    # Update weights
    weights = weights - lr*changes
    
    
    bias_change = np.sum(first_two)
    # Update Bias
    bias = bias - lr*bias_change

In [24]:
output = sig(np.dot(x,weights)+bias)
output

array([[7.51927155e-05],
       [3.82353313e-02],
       [3.82353313e-02],
       [9.54581842e-01]])