In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1,2,3, '5']
b = np.array(a, dtype=int)
print(b)
print(type(b))

[1 2 3 5]
<class 'numpy.ndarray'>


In [4]:
a = [[1,2,3],[4,5,6]]
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## np.zeros()

In [5]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [6]:
b = np.zeros((3,5), dtype=int)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

##  np.ones()

In [7]:
b = np.ones(3)
print(b)

[1. 1. 1.]


In [8]:
b = np.ones((4,5), dtype=int)
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##  np.full()
### size, fill_value are mandatory arguments

In [9]:
b = np.full(3, 5)
b

array([5, 5, 5])

In [10]:
b = np.full((3,5), 9, dtype=str)
print(b)

[['9' '9' '9' '9' '9']
 ['9' '9' '9' '9' '9']
 ['9' '9' '9' '9' '9']]


##  np.empty()
### used to create new aray witout initializing entries

In [11]:
b = np.empty(2)
b

array([4.24399158e-314, 1.06099790e-313])

In [12]:
b = np.empty([3,4], dtype=int)
b

array([[1919970921,  792355695,  959983919, 1630823479],
       [ 859190115, 1717710898,  842097462,  842622517],
       [1664377442,  929129015,        101,          0]])

## b = np.arange(start,stop,step,dtype)
### stop is mandatory

In [13]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(2,10,2,dtype=float)
b

array([2., 4., 6., 8.])

## np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0)

### using linspace() we have control over no. of evenly spaced samples generated within a given range [start,stop]

In [15]:
b = np.linspace(1,10)
b

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
b = np.linspace(2,10, 5, retstep=True, dtype=float, endpoint=False)
print(b)

(array([2. , 3.6, 5.2, 6.8, 8.4]), 1.6)


## np.identity()

In [17]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.eye()

In [18]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
b = np.eye(3,4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


##  np.random.rand()

In [20]:
# everytime you execute it returns random values
b = np.random.rand(10)
print(b)

[0.50128529 0.02479087 0.00837066 0.90885279 0.80216846 0.40897982
 0.88830036 0.17754816 0.10719949 0.11555546]


In [21]:
# To get values in range 0-10 we multiply each element by 10
b = np.random.rand(10)*10
print(b)

[7.35588208 7.97160293 1.03531516 2.08292395 3.62170985 0.19614556
 4.77223539 8.73829012 6.98482808 2.61683972]


In [22]:
# For 2d 
b = np.random.rand(2,3) # here 2,3 is not in form of tuple
print(b)

[[0.26606221 0.54700709 0.87319506]
 [0.88482576 0.44822137 0.63772716]]


## np.random.randint(low, high, size=None, dtype=int)

In [23]:
b = np.random.randint(1,10, size=3)
print(b)

[6 9 3]


In [24]:
b = np.random.randint(5, size=(2,4))
print(b)

[[0 4 2 4]
 [2 1 0 3]]


In [25]:
b = np.random.randint([1,9,7],10, size=3)
print(b)

[8 9 8]


##  Slicing and Indexing

In [26]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
print(li)
print(a)
print(a[:3])
print(a[2])

[1, 2, 3, 4, 5]
[ 4  3 16  8  5]
[ 4  3 16]
16


In [27]:
li_2d = [[j for j in range(i*4+1, i*4+5)] for i in range(5)]
print(li_2d)
arr_2d = np.array(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [28]:
print(arr_2d[:3, 2])
print(li_2d[:3][2])

[ 3  7 11]
[9, 10, 11, 12]


##  Mathematical operations

In [29]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,size=5)
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 2 19  6 11 14]
[15 13 18 18 19]


In [30]:
# Add 1 to every element
li = [1+i for i in li] # in case of list
print(li)

a = a+1 # in case of numpy array
print(a)

[2, 3, 4, 5, 6]
[ 3 20  7 12 15]


In [31]:
a = np.array([0,1,2,3,4])
b = np.array([0,1,0,3,4])
# Other mathematical opertions
d = a-b
e = a*b
f = a/b
g = a//b
h = a**b

print(a,b, d, e, f, g, h, sep="\n")

[0 1 2 3 4]
[0 1 0 3 4]
[0 0 2 0 0]
[ 0  1  0  9 16]
[nan  1. inf  1.  1.]
[0 1 0 1 1]
[  1   1   1  27 256]


c:\users\mehak\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
c:\users\mehak\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
c:\users\mehak\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  import sys


In [32]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())#min element index
print(a.max())
print(a.argmax())# max ele index

[0 1 2 3 4]
10
2.0
0
0
4
4


## Relational and logical operators

In [33]:
a = np.array([7,16,14,20,24])
b = np.array([12,11,11,4,16])

print(a<b)
print(a==b)

# logical operators
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))

[ True False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


##  Mathematical operations for 2-d array

In [34]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[13,14,15,16], [17,18,19,20]])
print(a)
print(b)

[[1 2 3 4]
 [5 6 7 8]]
[[13 14 15 16]
 [17 18 19 20]]


In [35]:
print(a+1)
print(b*2)

[[2 3 4 5]
 [6 7 8 9]]
[[26 28 30 32]
 [34 36 38 40]]


In [36]:
# Other mathematical opertions
d = a-b
e = a*b
f = a/b
g = a//b
h = a**b

print(a,b, d, e, f, g, h, sep="\n")

[[1 2 3 4]
 [5 6 7 8]]
[[13 14 15 16]
 [17 18 19 20]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[ 13  28  45  64]
 [ 85 108 133 160]]
[[0.07692308 0.14285714 0.2        0.25      ]
 [0.29411765 0.33333333 0.36842105 0.4       ]]
[[0 0 0 0]
 [0 0 0 0]]
[[          1       16384    14348907           0]
 [-1564725563  1159987200   442181591           0]]


In [37]:
c = np.array([1,2,3,4])
print(a,c,sep="\n")
print(a*c)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
[[ 1  4  9 16]
 [ 5 12 21 32]]


In [38]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())#min element index
print(a.max())
print(a.argmax())# max ele index
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
36
4.5
1
0
8
7
(2, 4)


##  Boolean 1-d indexing

In [39]:
print(b)
new_arr = b[(b>14) & (b<19)]
print(new_arr)

[[13 14 15 16]
 [17 18 19 20]]
[15 16 17 18]


In [40]:
c = np.array([14, 12, 7, 3, 19, 19, 3, 5])
c[:3] = 19
c[c>15] = 100
print(c)

[100 100 100   3 100 100   3   5]


## np.where()

In [41]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.array([100, 100, 100, 3, 100, 100, 3, 5])
print(a)
print(b)
ind = np.where(b==100) # (array([0, 1, 2, 4, 5], dtype=int32),)  
print(ind)
print(a[ind])
print(a[b==100])

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   3 100 100   3   5]
(array([0, 1, 2, 4, 5], dtype=int32),)
['t' 'b' 'r' 'e' 'f']
['t' 'b' 'r' 'e' 'f']


## Boolean-Indexing 2D array

In [42]:
arr = np.random.randint(1,30,(5,6))
print(arr)

[[24 13 11 27 14 19]
 [15 28  2 16  2  5]
 [17 21 20  5 23 19]
 [12 27 11 29 17 10]
 [10 23  8  8  2 23]]


In [43]:
bool_arr = arr>20
arr[bool_arr] = 100
print(arr)

[[100  13  11 100  14  19]
 [ 15 100   2  16   2   5]
 [ 17 100  20   5 100  19]
 [ 12 100  11 100  17  10]
 [ 10 100   8   8   2 100]]


In [44]:
# Update column 3 of arr where 100 is present
bool_arr = arr[:, 3]==100
print(bool_arr)
arr[bool_arr, 3] = 99
print(arr)

[ True False False  True False]
[[100  13  11  99  14  19]
 [ 15 100   2  16   2   5]
 [ 17 100  20   5 100  19]
 [ 12 100  11  99  17  10]
 [ 10 100   8   8   2 100]]


## 	numpy.sort(array, axis=-1, kind='quicksort', order=None)

If we don’t provide any value for ‘axis’ parameter then its default value is -1 i.e. it sort along the last axis which in 2D array is 1

In [45]:
# Create a 2D Numpy array list of list
arr_2d = np.array([[8, 7, 1, 2], [3, 2, 3, 1], [29, 32, 11, 9]])
print(arr_2d)

sort_by_row = np.sort(arr_2d, 1) # axis = 1 for rows
print(sort_by_row)

sort_by_col = np.sort(arr_2d, 0) # axis = 0 for column-wise
print(sort_by_col)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
[[ 1  2  7  8]
 [ 1  2  3  3]
 [ 9 11 29 32]]
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]


In [46]:
# Create a 2D Numpy array list of list
arr_2d = np.array([[21,20,19,18,17], [16,15,14,13,12], [11,10, 9, 8, 7], [6, 5, 4, 3, 2]])
print(arr_2d)

sort_by_col = np.sort(arr_2d, axis=0) # axis = 0 for column wise sorting
print(sort_by_col)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [5]:
import numpy as np
import csv

file_obj = open('C:/PYTHON/DataScience_Ninza/DataScience-and-ML/Datasets/year2017.csv')
data = csv.DictReader(file_obj, skipinitialspace=True)

killed=[]
country=[]
wounded=[]
for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])

np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded==''] = '0.0'

np_killed = np.array(np_killed, dtype=float)
np_wounded = np.array(np_wounded, dtype=float)

killed_wounded = np_killed+np_wounded
np_country = np.array(country)

bool_array = np_country=='India'
ans = killed_wounded[bool_array]

print(np.sum(ans)) # killed+wounded for India
print(np.sum(killed_wounded)) # Total killed+wounded

1167.0
51372.0
